
# ===================================================================
# DevOps Practice
#
# Defining server port 9090
# ===================================================================
server:
  port: 9090
